name: Continuous Integration

on: [push]

jobs:

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
        # checkout repository    
        - name: Checkout repository
          uses: actions/checkout@v3
        # setup python
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.11'        
        # install & configure poetry
        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
              virtualenvs-in-project: true
        # load cached venv if cache exists
        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
              path: .venv
              key: venv-{{ "${{ hashFiles('**/poetry.lock') }}" }}
        # install dependencies if cache does not exist
        - name: Install dependencies
          run: poetry install --no-interaction
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        # run linters
        - name: Run linters
          run: poetry run task lint
        # run tests
        - name: Run tests
          run: poetry run task test